/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fab.ewallet_project;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author cedri this shit is so fucking ugly i'm not even gonna lie
 */
public class Ewallet_frame extends javax.swing.JFrame {

    /**
     * Creates new form e-wallet_frame
     */
    public Ewallet_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUpTop = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        headerButtonsPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(32767, 0));
        accountName = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        accountMoney = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jButton7 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        menuPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50));
        transferButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        depositButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        accountButton = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        accountButton1 = new javax.swing.JButton();
        designPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        creatorsPanel = new javax.swing.JPanel();
        wilLabel = new javax.swing.JLabel();
        robiLabel = new javax.swing.JLabel();
        cliffLabel = new javax.swing.JLabel();
        cedLabel = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();
        transferPanelTitle = new javax.swing.JPanel();
        accDetailsPanel2 = new javax.swing.JLabel();
        transferLeftPurplePanel = new javax.swing.JPanel();
        transferRightPurplePanel = new javax.swing.JPanel();
        transferMainPanel = new javax.swing.JPanel();
        transfereeNumPanel = new javax.swing.JPanel();
        transferGrid1Panel = new javax.swing.JPanel();
        recipientPhoneLabel = new javax.swing.JLabel();
        transferGrid2Panel = new javax.swing.JPanel();
        transferNumberField = new javax.swing.JTextField();
        transferGrid3Panel = new javax.swing.JPanel();
        recipientAmountLabel = new javax.swing.JLabel();
        transferGrid4Panel = new javax.swing.JPanel();
        transferField = new javax.swing.JTextField();
        TransferNumpadPanel = new javax.swing.JPanel();
        TransferNumpad1 = new javax.swing.JButton();
        TransferNumpad2 = new javax.swing.JButton();
        TransferNumpad3 = new javax.swing.JButton();
        TransferNumpad4 = new javax.swing.JButton();
        TransferNumpad5 = new javax.swing.JButton();
        TransferNumpad6 = new javax.swing.JButton();
        TransferNumpad7 = new javax.swing.JButton();
        TransferNumpad8 = new javax.swing.JButton();
        TransferNumpad9 = new javax.swing.JButton();
        TransferNumpadDel = new javax.swing.JButton();
        TransferNumpad0 = new javax.swing.JButton();
        TransferNumpadTransfer = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        depositPanelTitle = new javax.swing.JPanel();
        accDetailsPanel1 = new javax.swing.JLabel();
        depositLeftPurplePanel = new javax.swing.JPanel();
        depositRightPurplePanel = new javax.swing.JPanel();
        depositMainLabel = new javax.swing.JPanel();
        depositQuestionPanel = new javax.swing.JPanel();
        depositQuestionLabel = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        numpadPanel = new javax.swing.JPanel();
        numpad1 = new javax.swing.JButton();
        numpad2 = new javax.swing.JButton();
        numpad3 = new javax.swing.JButton();
        numpad4 = new javax.swing.JButton();
        numpad5 = new javax.swing.JButton();
        numpad6 = new javax.swing.JButton();
        numpad7 = new javax.swing.JButton();
        numpad8 = new javax.swing.JButton();
        numpad9 = new javax.swing.JButton();
        numpadDel = new javax.swing.JButton();
        numpad0 = new javax.swing.JButton();
        numpadDeposit = new javax.swing.JButton();
        accountPanel = new javax.swing.JPanel();
        accountTopBorder = new javax.swing.JPanel();
        accDetailsPanel = new javax.swing.JLabel();
        accountMainPanel = new javax.swing.JPanel();
        accNamePanel = new javax.swing.JPanel();
        accNameLabel = new javax.swing.JLabel();
        accEmailLabel = new javax.swing.JLabel();
        accNamePanel1 = new javax.swing.JPanel();
        accNumberLabel = new javax.swing.JLabel();
        accPasswordLabel = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        accountShowPasswordBut = new javax.swing.JButton();
        accNumPanel = new javax.swing.JPanel();
        accountLogo = new javax.swing.JLabel();
        accPwPanel = new javax.swing.JPanel();
        deletePanel = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        rightPurplePanel = new javax.swing.JPanel();
        leftPurplePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paybuddy");
        setIconImage(setImageIcon());

        buttonUpTop.setBackground(new java.awt.Color(204, 204, 204));
        buttonUpTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonUpTop.setMaximumSize(new java.awt.Dimension(32767, 100));
        buttonUpTop.setPreferredSize(new java.awt.Dimension(883, 100));
        buttonUpTop.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo100x67.png"))); // NOI18N
        logoLabel.setText("PayBuddy");
        logoLabel.setToolTipText("");
        logoLabel.setMaximumSize(new java.awt.Dimension(250, 63));
        logoLabel.setMinimumSize(new java.awt.Dimension(120, 63));
        logoLabel.setPreferredSize(new java.awt.Dimension(250, 63));
        logoLabel.setRequestFocusEnabled(false);
        buttonUpTop.add(logoLabel, java.awt.BorderLayout.LINE_START);

        headerButtonsPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerButtonsPanel.setMinimumSize(new java.awt.Dimension(500, 100));
        headerButtonsPanel.setLayout(new javax.swing.BoxLayout(headerButtonsPanel, javax.swing.BoxLayout.X_AXIS));
        headerButtonsPanel.add(filler4);

        accountName.setBackground(new java.awt.Color(102, 0, 0));
        accountName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        accountName.setText("accountName");
        accountName.setAlignmentX(0.5F);
        if(SignupFrame.userAccount !=null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountName.setText("Hello, " + SignupFrame.userAccount.getPaybuddy().nameGetter() + "! You have a balance of: ");
        }
        else 
        {
            accountName.setText("Hello, Guest! You have a balance of:");
        }
        headerButtonsPanel.add(accountName);
        headerButtonsPanel.add(filler5);

        accountMoney.setBackground(new java.awt.Color(102, 0, 0));
        accountMoney.setFont(accountName.getFont());
        accountMoney.setText("accountMoney");
        accountMoney.setAlignmentX(0.5F);
        accountMoney.setMaximumSize(new java.awt.Dimension(125, 20));
        accountMoney.setMinimumSize(new java.awt.Dimension(125, 20));
        accountMoney.setPreferredSize(new java.awt.Dimension(125, 20));
        if (SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountMoney.setText("P" + SignupFrame.userAccount.getPaybuddy().moneyGetter());
        }
        else
        {
            accountMoney.setText("P 0.00");
        }
        headerButtonsPanel.add(accountMoney);
        headerButtonsPanel.add(filler6);

        jButton7.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 12)); // NOI18N
        jButton7.setText("Who made PayBuddy?");
        jButton7.setMaximumSize(new java.awt.Dimension(149, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(180, 30));
        headerButtonsPanel.add(jButton7);
        jButton7.addActionListener(e -> {
            if(currentCard.equals("card2"))
            {
                jButton7.setText("Switch back?");
            }
            else if(currentCard.equals("card4"))
            {
                jButton7.setText("Who made PayBuddy?");
            }
            String targetCard = getPreviousCard(currentCard);
            ((CardLayout)designPanel.getLayout()).show(designPanel, targetCard);
            currentCard = targetCard;
        });
        headerButtonsPanel.add(filler7);

        buttonUpTop.add(headerButtonsPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(buttonUpTop, java.awt.BorderLayout.PAGE_START);

        menuPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(300, 461));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonsPanel.add(filler3);

        transferButton.setBackground(new java.awt.Color(204, 204, 204));
        transferButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.setAlignmentX(0.5F);
        transferButton.setMaximumSize(new java.awt.Dimension(120, 70));
        transferButton.setPreferredSize(new java.awt.Dimension(75, 100));
        buttonsPanel.add(transferButton);
        transferButton.addActionListener(e ->
            {
                ((CardLayout)designPanel.getLayout()).show(designPanel, "card5");
            });
            buttonsPanel.add(filler1);

            depositButton.setBackground(new java.awt.Color(204, 204, 204));
            depositButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
            depositButton.setText("Deposit");
            depositButton.setAlignmentX(0.5F);
            depositButton.setMaximumSize(new java.awt.Dimension(120, 70));
            depositButton.setPreferredSize(new java.awt.Dimension(75, 100));
            buttonsPanel.add(depositButton);
            depositButton.addActionListener(e ->
                {
                    ((CardLayout)designPanel.getLayout()).show(designPanel, "card6");
                });
                buttonsPanel.add(filler2);

                accountButton.setBackground(new java.awt.Color(204, 204, 204));
                accountButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                accountButton.setText("Account");
                accountButton.setAlignmentX(0.5F);
                accountButton.setMaximumSize(new java.awt.Dimension(120, 70));
                accountButton.setPreferredSize(new java.awt.Dimension(75, 100));
                buttonsPanel.add(accountButton);
                accountButton.addActionListener(e ->
                    {
                        ((CardLayout)designPanel.getLayout()).show(designPanel, "card7");
                    });
                    buttonsPanel.add(filler10);

                    accountButton1.setBackground(new java.awt.Color(255, 153, 153));
                    accountButton1.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                    accountButton1.setText("Exit");
                    accountButton1.setAlignmentX(0.5F);
                    accountButton1.setMaximumSize(new java.awt.Dimension(120, 70));
                    accountButton1.setPreferredSize(new java.awt.Dimension(75, 100));
                    buttonsPanel.add(accountButton1);
                    accountButton1.addActionListener(e ->
                        {
                            System.exit(0);
                        });

                        menuPanel.add(buttonsPanel, java.awt.BorderLayout.LINE_START);

                        designPanel.setBackground(new java.awt.Color(102, 102, 102));
                        designPanel.setLayout(new java.awt.CardLayout());

                        imageLabel.setBackground(new java.awt.Color(153, 0, 51));
                        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
                        imageLabel.setPreferredSize(new java.awt.Dimension(500, 546));
                        designPanel.add(imageLabel, "card2");

                        creatorsPanel.setBackground(new java.awt.Color(102, 102, 102));
                        creatorsPanel.setLayout(new java.awt.GridLayout(2, 2));

                        wilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        wilLabel.setText("wil");
                        creatorsPanel.add(wilLabel);

                        robiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        robiLabel.setText("robi");
                        creatorsPanel.add(robiLabel);

                        cliffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cliffLabel.setText("cliff");
                        creatorsPanel.add(cliffLabel);

                        cedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cedLabel.setText("ced");
                        creatorsPanel.add(cedLabel);

                        designPanel.add(creatorsPanel, "card4");

                        transferPanel.setBackground(new java.awt.Color(255, 255, 255));
                        transferPanel.setLayout(new java.awt.BorderLayout());

                        transferPanelTitle.setBackground(new java.awt.Color(204, 204, 255));
                        transferPanelTitle.setPreferredSize(new java.awt.Dimension(50, 100));
                        transferPanelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

                        accDetailsPanel2.setBackground(new java.awt.Color(153, 102, 255));
                        accDetailsPanel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
                        accDetailsPanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        accDetailsPanel2.setText("Transfer");
                        accDetailsPanel2.setAlignmentY(0.0F);
                        accDetailsPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        accDetailsPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        accDetailsPanel2.setOpaque(true);
                        accDetailsPanel2.setPreferredSize(new java.awt.Dimension(300, 50));
                        transferPanelTitle.add(accDetailsPanel2);

                        transferPanel.add(transferPanelTitle, java.awt.BorderLayout.PAGE_START);

                        transferLeftPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                        transferLeftPurplePanel.setPreferredSize(new java.awt.Dimension(100, 10));
                        transferPanel.add(transferLeftPurplePanel, java.awt.BorderLayout.LINE_START);

                        transferRightPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                        transferRightPurplePanel.setPreferredSize(new java.awt.Dimension(100, 100));
                        transferPanel.add(transferRightPurplePanel, java.awt.BorderLayout.LINE_END);

                        transferMainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 255), 2, true));
                        transferMainPanel.setMaximumSize(new java.awt.Dimension(2147483647, 200));
                        transferMainPanel.setPreferredSize(new java.awt.Dimension(757, 200));
                        transferMainPanel.setLayout(new javax.swing.BoxLayout(transferMainPanel, javax.swing.BoxLayout.Y_AXIS));

                        transfereeNumPanel.setPreferredSize(new java.awt.Dimension(501, 0));
                        transfereeNumPanel.setLayout(new java.awt.GridLayout(2, 2));

                        transferGrid1Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 5, 25));

                        recipientPhoneLabel.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 14)); // NOI18N
                        recipientPhoneLabel.setText("Enter the recipient's phone number: ");
                        recipientPhoneLabel.setAlignmentX(0.5F);
                        recipientPhoneLabel.setPreferredSize(new java.awt.Dimension(252, 20));
                        transferGrid1Panel.add(recipientPhoneLabel);

                        transfereeNumPanel.add(transferGrid1Panel);

                        transferGrid2Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

                        transferNumberField.setColumns(30);
                        transferNumberField.setPreferredSize(new java.awt.Dimension(344, 40));
                        transferNumberField.addFocusListener(new FocusAdapter()
                            {
                                @Override
                                public void focusGained(FocusEvent e)
                                {   
                                    focusField = transferNumberField;
                                }
                            });
                            transferGrid2Panel.add(transferNumberField);

                            transfereeNumPanel.add(transferGrid2Panel);

                            transferGrid3Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 28));

                            recipientAmountLabel.setFont(new java.awt.Font("UD Digi Kyokasho N-B", 0, 14)); // NOI18N
                            recipientAmountLabel.setText("Enter desired amount:");
                            recipientAmountLabel.setAlignmentX(0.5F);
                            recipientAmountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                            transferGrid3Panel.add(recipientAmountLabel);

                            transfereeNumPanel.add(transferGrid3Panel);

                            transferGrid4Panel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

                            transferField.setColumns(30);
                            transferField.setPreferredSize(new java.awt.Dimension(344, 40));
                            transferField.addFocusListener(new FocusAdapter()
                                {
                                    @Override
                                    public void focusGained(FocusEvent e)
                                    {   
                                        focusField = transferField;
                                    }
                                });
                                transferGrid4Panel.add(transferField);

                                transfereeNumPanel.add(transferGrid4Panel);

                                transferMainPanel.add(transfereeNumPanel);

                                TransferNumpadPanel.setBackground(new java.awt.Color(255, 255, 255));
                                TransferNumpadPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                                TransferNumpadPanel.setLayout(new java.awt.GridLayout(4, 3));

                                TransferNumpad1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                                TransferNumpad1.setText("1");
                                TransferNumpad1.setPreferredSize(new java.awt.Dimension(90, 50));
                                TransferNumpad1.addActionListener(f ->
                                    {
                                        if(focusField == null)
                                        {
                                            return;
                                        }
                                        focusField.setText(focusField.getText() + "1");
                                    });
                                    TransferNumpadPanel.add(TransferNumpad1);

                                    TransferNumpad2.setFont(TransferNumpad1.getFont());
                                    TransferNumpad2.setText("2");
                                    TransferNumpad2.setPreferredSize(new java.awt.Dimension(90, 50));
                                    TransferNumpad2.addActionListener(f ->  
                                        {
                                            if(focusField == null)
                                            {
                                                return;
                                            }
                                            focusField.setText(focusField.getText() + "2");  
                                        });
                                        TransferNumpadPanel.add(TransferNumpad2);

                                        TransferNumpad3.setFont(TransferNumpad1.getFont());
                                        TransferNumpad3.setText("3");
                                        TransferNumpad3.setPreferredSize(new java.awt.Dimension(90, 50));
                                        TransferNumpad3.addActionListener(f ->  {
                                            if(focusField == null)
                                            {
                                                return;
                                            }
                                            focusField.setText(focusField.getText() + "3");
                                        });
                                        TransferNumpadPanel.add(TransferNumpad3);

                                        TransferNumpad4.setFont(TransferNumpad1.getFont());
                                        TransferNumpad4.setText("4");
                                        TransferNumpad4.setPreferredSize(new java.awt.Dimension(90, 50));
                                        TransferNumpad4.addActionListener(f ->
                                            {
                                                if(focusField == null)
                                                {
                                                    return;
                                                }
                                                focusField.setText(focusField.getText() + "4");
                                            });
                                            TransferNumpadPanel.add(TransferNumpad4);

                                            TransferNumpad5.setFont(TransferNumpad1.getFont());
                                            TransferNumpad5.setText("5");
                                            TransferNumpad5.setPreferredSize(new java.awt.Dimension(90, 50));
                                            TransferNumpad5.addActionListener(f ->
                                                {
                                                    if(focusField == null)
                                                    {
                                                        return;
                                                    }
                                                    focusField.setText(focusField.getText() + "5");
                                                });
                                                TransferNumpadPanel.add(TransferNumpad5);

                                                TransferNumpad6.setFont(TransferNumpad1.getFont());
                                                TransferNumpad6.setText("6");
                                                TransferNumpad6.setPreferredSize(new java.awt.Dimension(90, 50));
                                                TransferNumpad6.addActionListener(f ->  
                                                    {
                                                        if(focusField == null)
                                                        {
                                                            return;
                                                        }
                                                        focusField.setText(focusField.getText() + "6");  
                                                    });
                                                    TransferNumpadPanel.add(TransferNumpad6);

                                                    TransferNumpad7.setFont(TransferNumpad1.getFont());
                                                    TransferNumpad7.setText("7");
                                                    TransferNumpad7.setPreferredSize(new java.awt.Dimension(90, 50));
                                                    TransferNumpad7.addActionListener(f ->
                                                        {
                                                            if(focusField == null)
                                                            {
                                                                return;
                                                            }
                                                            focusField.setText(focusField.getText() + "7");
                                                        });
                                                        TransferNumpadPanel.add(TransferNumpad7);

                                                        TransferNumpad8.setFont(TransferNumpad1.getFont());
                                                        TransferNumpad8.setText("8");
                                                        TransferNumpad8.setPreferredSize(new java.awt.Dimension(90, 50));
                                                        TransferNumpad8.addActionListener(f ->
                                                            {
                                                                if(focusField == null)
                                                                {
                                                                    return;
                                                                }
                                                                focusField.setText(focusField.getText() + "8");
                                                            });
                                                            TransferNumpadPanel.add(TransferNumpad8);

                                                            TransferNumpad9.setFont(TransferNumpad1.getFont());
                                                            TransferNumpad9.setText("9");
                                                            TransferNumpad9.setPreferredSize(new java.awt.Dimension(90, 50));
                                                            TransferNumpad9.addActionListener(f ->
                                                                {
                                                                    if(focusField == null)
                                                                    {
                                                                        return;
                                                                    }
                                                                    focusField.setText(focusField.getText() + "9");
                                                                });
                                                                TransferNumpadPanel.add(TransferNumpad9);

                                                                TransferNumpadDel.setFont(TransferNumpad1.getFont());
                                                                TransferNumpadDel.setText("Delete");
                                                                TransferNumpadDel.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                TransferNumpadDel.addActionListener(f ->
                                                                    {
                                                                        if(focusField == null)
                                                                        {
                                                                            return;
                                                                        }

                                                                        if(!focusField.getText().isEmpty())
                                                                        {
                                                                            focusField.setText(focusField.getText().substring(0, focusField.getText().length() - 1));
                                                                        }
                                                                    });
                                                                    TransferNumpadPanel.add(TransferNumpadDel);

                                                                    TransferNumpad0.setFont(TransferNumpad1.getFont());
                                                                    TransferNumpad0.setText("0");
                                                                    TransferNumpad0.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                    TransferNumpad0.addActionListener(f ->
                                                                        {
                                                                            if(focusField == null)
                                                                            {
                                                                                return;
                                                                            }
                                                                            focusField.setText(focusField.getText() + "0");
                                                                        });
                                                                        TransferNumpadPanel.add(TransferNumpad0);

                                                                        TransferNumpadTransfer.setFont(TransferNumpad1.getFont());
                                                                        TransferNumpadTransfer.setText("Transfer");
                                                                        TransferNumpadTransfer.setAlignmentX(0.5F);
                                                                        TransferNumpadTransfer.setPreferredSize(new java.awt.Dimension(100, 40));
                                                                        TransferNumpadTransfer.addActionListener(f ->
                                                                            {
                                                                                if(transferField.getText().equals(""))
                                                                                {
                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Please enter an amount!","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                                                                }
                                                                                else if(!transferField.getText().matches("\\d*"))
                                                                                {
                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Enter a number please!","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                                                                    transferField.setText("");
                                                                                }
                                                                                else if(SignupFrame.userAccount.getPaybuddy().moneyGetter() < Integer.parseInt(transferField.getText()))
                                                                                {
                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"You do not have enough credits in your account to make this transfer!","",javax.swing.JOptionPane.OK_OPTION);
                                                                                }
                                                                                else if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                                                                                {   
                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Successfully transferred amount!","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                                                                    SignupFrame.userAccount.getPaybuddy().transfer(this);
                                                                                    transferField.setText("");
                                                                                    ((CardLayout)designPanel.getLayout()).show(designPanel, "card2");
                                                                                }
                                                                                else
                                                                                {
                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"cuh this doesn't work if since SignupFrame.java is what creates the account object that this frame uses for everyting :skull:","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                                                                }
                                                                            });
                                                                            TransferNumpadPanel.add(TransferNumpadTransfer);

                                                                            transferMainPanel.add(TransferNumpadPanel);

                                                                            transferPanel.add(transferMainPanel, java.awt.BorderLayout.CENTER);

                                                                            designPanel.add(transferPanel, "card5");

                                                                            depositPanel.setBackground(new java.awt.Color(255, 255, 255));
                                                                            depositPanel.setLayout(new java.awt.BorderLayout());

                                                                            depositPanelTitle.setBackground(new java.awt.Color(204, 204, 255));
                                                                            depositPanelTitle.setPreferredSize(new java.awt.Dimension(50, 100));
                                                                            depositPanelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

                                                                            accDetailsPanel1.setBackground(new java.awt.Color(153, 102, 255));
                                                                            accDetailsPanel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
                                                                            accDetailsPanel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                            accDetailsPanel1.setText("Deposit");
                                                                            accDetailsPanel1.setAlignmentY(0.0F);
                                                                            accDetailsPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                                                                            accDetailsPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                                                                            accDetailsPanel1.setOpaque(true);
                                                                            accDetailsPanel1.setPreferredSize(new java.awt.Dimension(300, 50));
                                                                            depositPanelTitle.add(accDetailsPanel1);

                                                                            depositPanel.add(depositPanelTitle, java.awt.BorderLayout.PAGE_START);

                                                                            depositLeftPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                                                                            depositLeftPurplePanel.setPreferredSize(new java.awt.Dimension(100, 100));
                                                                            depositPanel.add(depositLeftPurplePanel, java.awt.BorderLayout.LINE_START);

                                                                            depositRightPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                                                                            depositRightPurplePanel.setPreferredSize(new java.awt.Dimension(100, 100));
                                                                            depositPanel.add(depositRightPurplePanel, java.awt.BorderLayout.LINE_END);

                                                                            depositMainLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 255), 2, true));
                                                                            depositMainLabel.setLayout(new javax.swing.BoxLayout(depositMainLabel, javax.swing.BoxLayout.Y_AXIS));

                                                                            depositQuestionPanel.setMaximumSize(new java.awt.Dimension(2147483647, 30000));
                                                                            depositQuestionPanel.setPreferredSize(new java.awt.Dimension(420, 20));
                                                                            depositQuestionPanel.setLayout(new java.awt.GridBagLayout());

                                                                            depositQuestionLabel.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 18)); // NOI18N
                                                                            depositQuestionLabel.setText("Amount to deposit: ");
                                                                            depositQuestionPanel.add(depositQuestionLabel, new java.awt.GridBagConstraints());

                                                                            depositField.setColumns(25);
                                                                            depositQuestionPanel.add(depositField, new java.awt.GridBagConstraints());

                                                                            depositMainLabel.add(depositQuestionPanel);

                                                                            numpadPanel.setBackground(new java.awt.Color(255, 255, 255));
                                                                            numpadPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                                                                            numpadPanel.setLayout(new java.awt.GridLayout(4, 3));

                                                                            numpad1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
                                                                            numpad1.setText("1");
                                                                            numpad1.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                            numpad1.addActionListener(f ->
                                                                                {
                                                                                    depositField.setText(depositField.getText() + "1");
                                                                                });
                                                                                numpadPanel.add(numpad1);

                                                                                numpad2.addActionListener(f ->
                                                                                    {
                                                                                        depositField.setText(depositField.getText() + "2");
                                                                                    });
                                                                                    numpad2.setFont(numpad1.getFont());
                                                                                    numpad2.setText("2");
                                                                                    numpad2.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                    numpadPanel.add(numpad2);

                                                                                    numpad3.addActionListener(f ->
                                                                                        {
                                                                                            depositField.setText(depositField.getText() + "3");
                                                                                        });
                                                                                        numpad3.setFont(numpad1.getFont());
                                                                                        numpad3.setText("3");
                                                                                        numpad3.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                        numpadPanel.add(numpad3);

                                                                                        numpad4.setFont(numpad1.getFont());
                                                                                        numpad4.setText("4");
                                                                                        numpad4.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                        numpad4.addActionListener(f ->
                                                                                            {
                                                                                                depositField.setText(depositField.getText() + "4");
                                                                                            });
                                                                                            numpadPanel.add(numpad4);

                                                                                            numpad5.setFont(numpad1.getFont());
                                                                                            numpad5.setText("5");
                                                                                            numpad5.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                            numpad5.addActionListener(f ->
                                                                                                {
                                                                                                    depositField.setText(depositField.getText() + "5");
                                                                                                });
                                                                                                numpadPanel.add(numpad5);

                                                                                                numpad6.addActionListener(f ->
                                                                                                    {
                                                                                                        depositField.setText(depositField.getText() + "6");
                                                                                                    });
                                                                                                    numpad6.setFont(numpad1.getFont());
                                                                                                    numpad6.setText("6");
                                                                                                    numpad6.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                    numpadPanel.add(numpad6);

                                                                                                    numpad7.setFont(numpad1.getFont());
                                                                                                    numpad7.setText("7");
                                                                                                    numpad7.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                    numpad7.addActionListener(f ->
                                                                                                        {
                                                                                                            depositField.setText(depositField.getText() + "7");
                                                                                                        });
                                                                                                        numpadPanel.add(numpad7);

                                                                                                        numpad8.setFont(numpad1.getFont());
                                                                                                        numpad8.setText("8");
                                                                                                        numpad8.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                        numpad8.addActionListener(f ->
                                                                                                            {
                                                                                                                depositField.setText(depositField.getText() + "8");
                                                                                                            });
                                                                                                            numpadPanel.add(numpad8);

                                                                                                            numpad9.setFont(numpad1.getFont());
                                                                                                            numpad9.setText("9");
                                                                                                            numpad9.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                            numpad9.addActionListener(f ->
                                                                                                                {
                                                                                                                    depositField.setText(depositField.getText() + "9");
                                                                                                                });
                                                                                                                numpadPanel.add(numpad9);

                                                                                                                numpadDel.setFont(numpad1.getFont());
                                                                                                                numpadDel.setText("Delete");
                                                                                                                numpadDel.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                                numpadDel.addActionListener(f ->
                                                                                                                    {
                                                                                                                        if(!depositField.getText().isEmpty())
                                                                                                                        {
                                                                                                                            depositField.setText(depositField.getText().substring(0, depositField.getText().length() - 1));
                                                                                                                        }
                                                                                                                    });
                                                                                                                    numpadPanel.add(numpadDel);

                                                                                                                    numpad0.setFont(numpad1.getFont());
                                                                                                                    numpad0.setText("0");
                                                                                                                    numpad0.setPreferredSize(new java.awt.Dimension(90, 50));
                                                                                                                    numpad0.addActionListener(f ->
                                                                                                                        {
                                                                                                                            depositField.setText(depositField.getText() + "0");
                                                                                                                        });
                                                                                                                        numpadPanel.add(numpad0);

                                                                                                                        numpadDeposit.setFont(numpad1.getFont());
                                                                                                                        numpadDeposit.setText("Deposit");
                                                                                                                        numpadDeposit.setAlignmentX(0.5F);
                                                                                                                        numpadDeposit.setPreferredSize(new java.awt.Dimension(100, 40));
                                                                                                                        numpadDeposit.addActionListener(f ->
                                                                                                                            {
                                                                                                                                if(depositField.getText().equals(""))
                                                                                                                                {
                                                                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Please enter an amount!","",javax.swing.JOptionPane.WARNING_MESSAGE);
                                                                                                                                }
                                                                                                                                else if(!depositField.getText().matches("\\d*"))
                                                                                                                                {
                                                                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Enter a number please!","",javax.swing.JOptionPane.WARNING_MESSAGE);
                                                                                                                                }
                                                                                                                                else if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                                                                                                                                {
                                                                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"Successfully deposited amount!","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                                                                                                                    SignupFrame.userAccount.getPaybuddy().deposit(this);
                                                                                                                                    depositField.setText("");
                                                                                                                                    ((CardLayout)designPanel.getLayout()).show(designPanel, "card2");
                                                                                                                                }
                                                                                                                                else
                                                                                                                                {
                                                                                                                                    javax.swing.JOptionPane.showMessageDialog(null,"cuh this doesn't work if since SignupFrame.java is what creates the account object that this frame uses for everyting :skull:","",javax.swing.JOptionPane.WARNING_MESSAGE);
                                                                                                                                }
                                                                                                                            });
                                                                                                                            numpadPanel.add(numpadDeposit);

                                                                                                                            depositMainLabel.add(numpadPanel);

                                                                                                                            depositPanel.add(depositMainLabel, java.awt.BorderLayout.CENTER);

                                                                                                                            designPanel.add(depositPanel, "card6");

                                                                                                                            accountPanel.setLayout(new java.awt.BorderLayout());

                                                                                                                            accountTopBorder.setBackground(new java.awt.Color(204, 204, 255));
                                                                                                                            accountTopBorder.setPreferredSize(new java.awt.Dimension(100, 100));
                                                                                                                            accountTopBorder.setLayout(new java.awt.GridBagLayout());

                                                                                                                            accDetailsPanel.setBackground(new java.awt.Color(153, 102, 255));
                                                                                                                            accDetailsPanel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
                                                                                                                            accDetailsPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                            accDetailsPanel.setText("Account Details");
                                                                                                                            accDetailsPanel.setAlignmentY(0.0F);
                                                                                                                            accDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                                                                                                                            accDetailsPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                                                                                                                            accDetailsPanel.setOpaque(true);
                                                                                                                            accDetailsPanel.setPreferredSize(new java.awt.Dimension(300, 50));
                                                                                                                            accountTopBorder.add(accDetailsPanel, new java.awt.GridBagConstraints());

                                                                                                                            accountPanel.add(accountTopBorder, java.awt.BorderLayout.PAGE_START);

                                                                                                                            accountMainPanel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                            accountMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 2));
                                                                                                                            accountMainPanel.setLayout(new javax.swing.BoxLayout(accountMainPanel, javax.swing.BoxLayout.Y_AXIS));

                                                                                                                            accNamePanel.setBackground(new java.awt.Color(255, 255, 255));

                                                                                                                            accNameLabel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                            accNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                                                                                                                            accNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                            accNameLabel.setText("Account Name");
                                                                                                                            accNameLabel.setAlignmentY(0.0F);
                                                                                                                            accNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 2));
                                                                                                                            accNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                                                                                                                            accNameLabel.setOpaque(true);
                                                                                                                            accNameLabel.setPreferredSize(new java.awt.Dimension(270, 40));
                                                                                                                            if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null) 
                                                                                                                            {
                                                                                                                                accNameLabel.setText("Account name: " + SignupFrame.userAccount.getPaybuddy().nameGetter());
                                                                                                                            }
                                                                                                                            else
                                                                                                                            {
                                                                                                                                accNameLabel.setText("Guest");
                                                                                                                            }
                                                                                                                            accNamePanel.add(accNameLabel);

                                                                                                                            accEmailLabel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                            accEmailLabel.setFont(accNameLabel.getFont());
                                                                                                                            accEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                            accEmailLabel.setText("Account Email");
                                                                                                                            accEmailLabel.setAlignmentY(0.0F);
                                                                                                                            accEmailLabel.setBorder(accNameLabel.getBorder());
                                                                                                                            accEmailLabel.setOpaque(true);
                                                                                                                            accEmailLabel.setPreferredSize(new java.awt.Dimension(270, 40));
                                                                                                                            if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                                                                                                                            {
                                                                                                                                accEmailLabel.setText("Account Email: " + SignupFrame.userAccount.getPaybuddy().emailGetter());
                                                                                                                            }
                                                                                                                            else
                                                                                                                            {
                                                                                                                                accEmailLabel.setText("Guest");
                                                                                                                            }
                                                                                                                            accNamePanel.add(accEmailLabel);

                                                                                                                            accountMainPanel.add(accNamePanel);

                                                                                                                            accNamePanel1.setBackground(new java.awt.Color(255, 255, 255));

                                                                                                                            accNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                            accNumberLabel.setFont(accNameLabel.getFont());
                                                                                                                            accNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                            accNumberLabel.setText("Account Number");
                                                                                                                            accNumberLabel.setToolTipText("");
                                                                                                                            accNumberLabel.setBorder(accNameLabel.getBorder());
                                                                                                                            accNumberLabel.setDoubleBuffered(true);
                                                                                                                            accNumberLabel.setOpaque(true);
                                                                                                                            accNumberLabel.setPreferredSize(new java.awt.Dimension(270, 40));
                                                                                                                            if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                                                                                                                            {
                                                                                                                                accNumberLabel.setText("Account Number: " + SignupFrame.userAccount.getPaybuddy().numberGetter());
                                                                                                                            }
                                                                                                                            else
                                                                                                                            {
                                                                                                                                accNumberLabel.setText("Guest Number");
                                                                                                                            }
                                                                                                                            accNamePanel1.add(accNumberLabel);

                                                                                                                            accPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                            accPasswordLabel.setFont(accNameLabel.getFont());
                                                                                                                            accPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                                                                                                                            accPasswordLabel.setText("Account Password");
                                                                                                                            accPasswordLabel.setAlignmentY(0.0F);
                                                                                                                            accPasswordLabel.setBorder(accNameLabel.getBorder());
                                                                                                                            accPasswordLabel.setOpaque(true);
                                                                                                                            accPasswordLabel.setPreferredSize(new java.awt.Dimension(270, 40));
                                                                                                                            if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                                                                                                                            {
                                                                                                                                accPasswordLabel.setText("*".repeat(accPasswordLabel.getText().length()));
                                                                                                                            }
                                                                                                                            else
                                                                                                                            {
                                                                                                                                accPasswordLabel.setText("N/A");
                                                                                                                            }
                                                                                                                            accNamePanel1.add(accPasswordLabel);

                                                                                                                            accountMainPanel.add(accNamePanel1);

                                                                                                                            passwordPanel.setBackground(new java.awt.Color(255, 255, 255));

                                                                                                                            accountShowPasswordBut.setBackground(new java.awt.Color(153, 153, 255));
                                                                                                                            accountShowPasswordBut.setText("Show password?");
                                                                                                                            accountShowPasswordBut.addActionListener(f ->
                                                                                                                                {
                                                                                                                                    if(accountShowPasswordBut.getText().equals("Show password?"))
                                                                                                                                    {
                                                                                                                                        accountShowPasswordBut.setText("Hide password?");
                                                                                                                                        accPasswordLabel.setText("Account Password: " + SignupFrame.userAccount.getPaybuddy().pwGetter());
                                                                                                                                    }
                                                                                                                                    else
                                                                                                                                    {
                                                                                                                                        accountShowPasswordBut.setText("Show password?");
                                                                                                                                        accPasswordLabel.setText("*".repeat(accPasswordLabel.getText().length()));
                                                                                                                                    }
                                                                                                                                });
                                                                                                                                passwordPanel.add(accountShowPasswordBut);

                                                                                                                                accountMainPanel.add(passwordPanel);

                                                                                                                                accNumPanel.setBackground(new java.awt.Color(255, 255, 255));

                                                                                                                                accountLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo100x67.png"))); // NOI18N
                                                                                                                                accountLogo.setAlignmentX(0.5F);
                                                                                                                                accNumPanel.add(accountLogo);

                                                                                                                                accountMainPanel.add(accNumPanel);

                                                                                                                                accPwPanel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                                accountMainPanel.add(accPwPanel);

                                                                                                                                deletePanel.setBackground(new java.awt.Color(255, 255, 255));
                                                                                                                                deletePanel.setPreferredSize(new java.awt.Dimension(138, 50));
                                                                                                                                deletePanel.setLayout(new javax.swing.BoxLayout(deletePanel, javax.swing.BoxLayout.Y_AXIS));

                                                                                                                                deleteButton.setBackground(new java.awt.Color(153, 51, 255));
                                                                                                                                deleteButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 14)); // NOI18N
                                                                                                                                deleteButton.setText("Perish account");
                                                                                                                                deleteButton.setAlignmentX(0.5F);
                                                                                                                                deleteButton.addActionListener(f ->
                                                                                                                                    {
                                                                                                                                        SignupFrame.userAccount.getPaybuddy().perish();
                                                                                                                                        dispose();
                                                                                                                                        new SignupFrame().setVisible(true);
                                                                                                                                    });
                                                                                                                                    deletePanel.add(deleteButton);

                                                                                                                                    accountMainPanel.add(deletePanel);

                                                                                                                                    accountPanel.add(accountMainPanel, java.awt.BorderLayout.CENTER);

                                                                                                                                    rightPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                                                                                                                                    rightPurplePanel.setMinimumSize(new java.awt.Dimension(100, 10));
                                                                                                                                    rightPurplePanel.setPreferredSize(new java.awt.Dimension(100, 10));
                                                                                                                                    accountPanel.add(rightPurplePanel, java.awt.BorderLayout.LINE_END);

                                                                                                                                    leftPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                                                                                                                                    leftPurplePanel.setPreferredSize(new java.awt.Dimension(100, 10));
                                                                                                                                    accountPanel.add(leftPurplePanel, java.awt.BorderLayout.LINE_START);

                                                                                                                                    designPanel.add(accountPanel, "card7");

                                                                                                                                    menuPanel.add(designPanel, java.awt.BorderLayout.CENTER);

                                                                                                                                    getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);

                                                                                                                                    pack();
                                                                                                                                    setLocationRelativeTo(null);
                                                                                                                                }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ewallet_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransferNumpad0;
    private javax.swing.JButton TransferNumpad1;
    private javax.swing.JButton TransferNumpad2;
    private javax.swing.JButton TransferNumpad3;
    private javax.swing.JButton TransferNumpad4;
    private javax.swing.JButton TransferNumpad5;
    private javax.swing.JButton TransferNumpad6;
    private javax.swing.JButton TransferNumpad7;
    private javax.swing.JButton TransferNumpad8;
    private javax.swing.JButton TransferNumpad9;
    private javax.swing.JButton TransferNumpadDel;
    private javax.swing.JPanel TransferNumpadPanel;
    private javax.swing.JButton TransferNumpadTransfer;
    private javax.swing.JLabel accDetailsPanel;
    private javax.swing.JLabel accDetailsPanel1;
    private javax.swing.JLabel accDetailsPanel2;
    private javax.swing.JLabel accEmailLabel;
    private javax.swing.JLabel accNameLabel;
    private javax.swing.JPanel accNamePanel;
    private javax.swing.JPanel accNamePanel1;
    private javax.swing.JPanel accNumPanel;
    private javax.swing.JLabel accNumberLabel;
    private javax.swing.JLabel accPasswordLabel;
    private javax.swing.JPanel accPwPanel;
    private javax.swing.JButton accountButton;
    private javax.swing.JButton accountButton1;
    private javax.swing.JLabel accountLogo;
    private javax.swing.JPanel accountMainPanel;
    private javax.swing.JLabel accountMoney;
    private javax.swing.JLabel accountName;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JButton accountShowPasswordBut;
    private javax.swing.JPanel accountTopBorder;
    private javax.swing.JPanel buttonUpTop;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cedLabel;
    private javax.swing.JLabel cliffLabel;
    private javax.swing.JPanel creatorsPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JPanel depositLeftPurplePanel;
    private javax.swing.JPanel depositMainLabel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JPanel depositPanelTitle;
    private javax.swing.JLabel depositQuestionLabel;
    private javax.swing.JPanel depositQuestionPanel;
    private javax.swing.JPanel depositRightPurplePanel;
    private javax.swing.JPanel designPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel headerButtonsPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel leftPurplePanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton numpad0;
    private javax.swing.JButton numpad1;
    private javax.swing.JButton numpad2;
    private javax.swing.JButton numpad3;
    private javax.swing.JButton numpad4;
    private javax.swing.JButton numpad5;
    private javax.swing.JButton numpad6;
    private javax.swing.JButton numpad7;
    private javax.swing.JButton numpad8;
    private javax.swing.JButton numpad9;
    private javax.swing.JButton numpadDel;
    private javax.swing.JButton numpadDeposit;
    private javax.swing.JPanel numpadPanel;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel recipientAmountLabel;
    private javax.swing.JLabel recipientPhoneLabel;
    private javax.swing.JPanel rightPurplePanel;
    private javax.swing.JLabel robiLabel;
    private javax.swing.JButton transferButton;
    private javax.swing.JTextField transferField;
    private javax.swing.JPanel transferGrid1Panel;
    private javax.swing.JPanel transferGrid2Panel;
    private javax.swing.JPanel transferGrid3Panel;
    private javax.swing.JPanel transferGrid4Panel;
    private javax.swing.JPanel transferLeftPurplePanel;
    private javax.swing.JPanel transferMainPanel;
    private javax.swing.JTextField transferNumberField;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JPanel transferPanelTitle;
    private javax.swing.JPanel transferRightPurplePanel;
    private javax.swing.JPanel transfereeNumPanel;
    private javax.swing.JLabel wilLabel;
    // End of variables declaration//GEN-END:variables

    // my variable declarations
    private String currentCard = "card2";
    protected javax.swing.JTextField focusField;
    // end of my variable declarations

    // user methods
    private String getPreviousCard(String current) {
        return switch (current) {
            case "card4" ->
                "card2";
            case "card2" ->
                "card4";
            default ->
                "card1";
        };
    }

    private Image setImageIcon() {
        java.net.URL url = getClass().getResource("/main/resources/logo100x67.png");
        if (url != null) {
            return new ImageIcon(url).getImage();
        } else {
            return null;
        }
    }
    // end of user methods

    // component getters
    public javax.swing.JTextField getDepositField() {
        return depositField;
    }

    public javax.swing.JTextField getTransferField() {
        return transferField;
    }

    public javax.swing.JLabel getMoneyLabel() {
        return accountMoney;
    }
    // end of component getters
}

class paybuddyAccount {

    private paybuddy userAccount;

    public paybuddyAccount(paybuddy userAccount) {
        this.userAccount = userAccount;
    }

    public paybuddy getPaybuddy() {
        return this.userAccount;
    }
}
