/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fab.ewallet_project;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author cedri
 */



public class Ewallet_frame extends javax.swing.JFrame {

    /**
     * Creates new form e-wallet_frame
     */
    public Ewallet_frame() {
        initComponents();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonUpTop = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        headerButtonsPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(32767, 0));
        accountName = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        accountMoney = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jButton7 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        menuPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50));
        transferButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        depositButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        accountButton = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        accountButton1 = new javax.swing.JButton();
        designPanel = new javax.swing.JPanel();
        creatorsPanel = new javax.swing.JPanel();
        wilLabel = new javax.swing.JLabel();
        robiLabel = new javax.swing.JLabel();
        cliffLabel = new javax.swing.JLabel();
        cedLabel = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        despositPanel = new javax.swing.JPanel();
        Deposit_Top_Border = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Deposit_Main_Panel = new javax.swing.JPanel();
        Enter_Amounr_Label = new javax.swing.JLabel();
        Deposit_Amount = new javax.swing.JTextField();
        accountPanel = new javax.swing.JPanel();
        accountTopBorder = new javax.swing.JPanel();
        accDetailsPanel = new javax.swing.JLabel();
        accountMainPanel = new javax.swing.JPanel();
        accNamePanel = new javax.swing.JPanel();
        accNameLabel = new javax.swing.JLabel();
        accEmailPanel = new javax.swing.JPanel();
        accEmailLabel = new javax.swing.JLabel();
        accNumPanel = new javax.swing.JPanel();
        Account_Label_Number = new javax.swing.JLabel();
        accPwPanel = new javax.swing.JPanel();
        Account_Label_Password = new javax.swing.JLabel();
        deletePanel = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        leftPurplePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paybuddy");
        setIconImage(setImageIcon());

        buttonUpTop.setBackground(new java.awt.Color(204, 204, 204));
        buttonUpTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonUpTop.setMaximumSize(new java.awt.Dimension(32767, 100));
        buttonUpTop.setPreferredSize(new java.awt.Dimension(883, 100));
        buttonUpTop.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo100x67.png"))); // NOI18N
        logoLabel.setText("PayBuddy");
        logoLabel.setToolTipText("");
        logoLabel.setMaximumSize(new java.awt.Dimension(250, 63));
        logoLabel.setMinimumSize(new java.awt.Dimension(120, 63));
        logoLabel.setPreferredSize(new java.awt.Dimension(250, 63));
        logoLabel.setRequestFocusEnabled(false);
        buttonUpTop.add(logoLabel, java.awt.BorderLayout.LINE_START);

        headerButtonsPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerButtonsPanel.setMinimumSize(new java.awt.Dimension(500, 100));
        headerButtonsPanel.setLayout(new javax.swing.BoxLayout(headerButtonsPanel, javax.swing.BoxLayout.X_AXIS));
        headerButtonsPanel.add(filler4);

        accountName.setBackground(new java.awt.Color(102, 0, 0));
        accountName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        accountName.setText("accountName");
        accountName.setAlignmentX(0.5F);
        if(SignupFrame.userAccount !=null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountName.setText("Hello, " + SignupFrame.userAccount.getPaybuddy().nameGetter() + "!");
        }
        else 
        {
            accountName.setText("Hello, Guest!");
        }
        headerButtonsPanel.add(accountName);
        headerButtonsPanel.add(filler5);

        accountMoney.setBackground(new java.awt.Color(102, 0, 0));
        accountMoney.setFont(accountName.getFont());
        accountMoney.setText("accountMoney");
        accountMoney.setAlignmentX(0.5F);
        accountMoney.setMaximumSize(new java.awt.Dimension(125, 20));
        accountMoney.setMinimumSize(new java.awt.Dimension(125, 20));
        accountMoney.setPreferredSize(new java.awt.Dimension(125, 20));
        if (SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountMoney.setText("- P" + SignupFrame.userAccount.getPaybuddy().moneyGetter());
        }
        else
        {
            accountMoney.setText("P 0.00");
        }
        headerButtonsPanel.add(accountMoney);
        headerButtonsPanel.add(filler6);

        jButton7.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 12)); // NOI18N
        jButton7.setText("Who made PayBuddy?");
        jButton7.setMaximumSize(new java.awt.Dimension(149, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(180, 30));
        headerButtonsPanel.add(jButton7);
        jButton7.addActionListener(e -> {
            if(currentCard.equals("card2"))
            {
                jButton7.setText("Switch back?");
            }
            else if(currentCard.equals("card4"))
            {
                jButton7.setText("Who made PayBuddy?");
            }
            String targetCard = getPreviousCard(currentCard);
            ((CardLayout)designPanel.getLayout()).show(designPanel, targetCard);
            currentCard = targetCard;
        });
        headerButtonsPanel.add(filler7);

        buttonUpTop.add(headerButtonsPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(buttonUpTop, java.awt.BorderLayout.PAGE_START);

        menuPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(300, 461));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonsPanel.add(filler3);

        transferButton.setBackground(new java.awt.Color(204, 204, 204));
        transferButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.setAlignmentX(0.5F);
        transferButton.setMaximumSize(new java.awt.Dimension(120, 70));
        transferButton.setPreferredSize(new java.awt.Dimension(75, 100));
        buttonsPanel.add(transferButton);
        transferButton.addActionListener(e ->
            {
                ((CardLayout)designPanel.getLayout()).show(designPanel, "card5");
            });
            buttonsPanel.add(filler1);

            depositButton.setBackground(new java.awt.Color(204, 204, 204));
            depositButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
            depositButton.setText("Deposit");
            depositButton.setAlignmentX(0.5F);
            depositButton.setMaximumSize(new java.awt.Dimension(120, 70));
            depositButton.setPreferredSize(new java.awt.Dimension(75, 100));
            depositButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    depositButtonActionPerformed(evt);
                }
            });
            buttonsPanel.add(depositButton);
            depositButton.addActionListener(e ->
                {
                    ((CardLayout)designPanel.getLayout()).show(designPanel, "card6");
                });
                buttonsPanel.add(filler2);

                accountButton.setBackground(new java.awt.Color(204, 204, 204));
                accountButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                accountButton.setText("Account");
                accountButton.setAlignmentX(0.5F);
                accountButton.setMaximumSize(new java.awt.Dimension(120, 70));
                accountButton.setPreferredSize(new java.awt.Dimension(75, 100));
                buttonsPanel.add(accountButton);
                accountButton.addActionListener(e ->
                    {
                        ((CardLayout)designPanel.getLayout()).show(designPanel, "card7");
                    });
                    buttonsPanel.add(filler10);

                    accountButton1.setBackground(new java.awt.Color(255, 153, 153));
                    accountButton1.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                    accountButton1.setText("Exit");
                    accountButton1.setAlignmentX(0.5F);
                    accountButton1.setMaximumSize(new java.awt.Dimension(120, 70));
                    accountButton1.setPreferredSize(new java.awt.Dimension(75, 100));
                    buttonsPanel.add(accountButton1);
                    accountButton1.addActionListener(e ->
                        {
                            System.exit(0);
                        });

                        menuPanel.add(buttonsPanel, java.awt.BorderLayout.LINE_START);

                        designPanel.setBackground(new java.awt.Color(102, 102, 102));
                        designPanel.setLayout(new java.awt.CardLayout());

                        creatorsPanel.setBackground(new java.awt.Color(102, 102, 102));
                        creatorsPanel.setLayout(new java.awt.GridLayout(2, 2));

                        wilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        wilLabel.setText("wil");
                        creatorsPanel.add(wilLabel);

                        robiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        robiLabel.setText("robi");
                        creatorsPanel.add(robiLabel);

                        cliffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cliffLabel.setText("cliff");
                        creatorsPanel.add(cliffLabel);

                        cedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cedLabel.setText("ced");
                        creatorsPanel.add(cedLabel);

                        designPanel.add(creatorsPanel, "card4");

                        transferPanel.setBackground(new java.awt.Color(255, 255, 255));

                        jLabel1.setText("transfer");
                        transferPanel.add(jLabel1);

                        designPanel.add(transferPanel, "card5");

                        despositPanel.setBackground(new java.awt.Color(255, 255, 255));
                        despositPanel.setLayout(new java.awt.BorderLayout());

                        Deposit_Top_Border.setBackground(new java.awt.Color(204, 204, 255));
                        Deposit_Top_Border.setPreferredSize(new java.awt.Dimension(100, 200));

                        jLabel2.setBackground(new java.awt.Color(153, 51, 255));
                        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
                        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        jLabel2.setText("Deposit");
                        jLabel2.setAlignmentY(0.0F);
                        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        jLabel2.setOpaque(true);
                        jLabel2.setPreferredSize(new java.awt.Dimension(200, 40));
                        Deposit_Top_Border.add(jLabel2);

                        despositPanel.add(Deposit_Top_Border, java.awt.BorderLayout.PAGE_START);

                        Deposit_Main_Panel.setBackground(new java.awt.Color(204, 204, 255));
                        Deposit_Main_Panel.setAlignmentX(0.0F);
                        Deposit_Main_Panel.setAlignmentY(0.0F);

                        Enter_Amounr_Label.setBackground(new java.awt.Color(153, 0, 255));
                        Enter_Amounr_Label.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
                        Enter_Amounr_Label.setText("Enter Amount:");
                        Enter_Amounr_Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        Enter_Amounr_Label.setOpaque(true);
                        Enter_Amounr_Label.setPreferredSize(new java.awt.Dimension(150, 30));
                        Deposit_Main_Panel.add(Enter_Amounr_Label);

                        Deposit_Amount.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
                        Deposit_Amount.setPreferredSize(new java.awt.Dimension(100, 25));
                        Deposit_Main_Panel.add(Deposit_Amount);

                        despositPanel.add(Deposit_Main_Panel, java.awt.BorderLayout.CENTER);

                        designPanel.add(despositPanel, "card6");

                        accountPanel.setLayout(new java.awt.BorderLayout());

                        accountTopBorder.setBackground(new java.awt.Color(204, 204, 255));
                        accountTopBorder.setPreferredSize(new java.awt.Dimension(100, 100));
                        accountTopBorder.setLayout(new java.awt.GridBagLayout());

                        accDetailsPanel.setBackground(new java.awt.Color(153, 102, 255));
                        accDetailsPanel.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
                        accDetailsPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        accDetailsPanel.setText("Account Details");
                        accDetailsPanel.setAlignmentY(0.0F);
                        accDetailsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                        accDetailsPanel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        accDetailsPanel.setOpaque(true);
                        accDetailsPanel.setPreferredSize(new java.awt.Dimension(300, 50));
                        accountTopBorder.add(accDetailsPanel, new java.awt.GridBagConstraints());

                        accountPanel.add(accountTopBorder, java.awt.BorderLayout.PAGE_START);

                        accountMainPanel.setBackground(new java.awt.Color(255, 255, 255));
                        accountMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 255), 2));
                        accountMainPanel.setLayout(new javax.swing.BoxLayout(accountMainPanel, javax.swing.BoxLayout.Y_AXIS));

                        accNamePanel.setBackground(new java.awt.Color(255, 255, 255));

                        accNameLabel.setBackground(new java.awt.Color(255, 255, 255));
                        accNameLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
                        accNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        accNameLabel.setText("Account Name");
                        accNameLabel.setAlignmentY(0.0F);
                        accNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 2));
                        accNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                        accNameLabel.setOpaque(true);
                        accNameLabel.setPreferredSize(new java.awt.Dimension(250, 30));
                        if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null) 
                        {
                            accNameLabel.setText("Account name: " + SignupFrame.userAccount.getPaybuddy().nameGetter());
                        }
                        else
                        {
                            accNameLabel.setText("Guest");
                        }
                        accNamePanel.add(accNameLabel);

                        accountMainPanel.add(accNamePanel);

                        accEmailPanel.setBackground(new java.awt.Color(255, 255, 255));

                        accEmailLabel.setBackground(new java.awt.Color(255, 255, 255));
                        accEmailLabel.setFont(accNameLabel.getFont());
                        accEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        accEmailLabel.setText("Account Email");
                        accEmailLabel.setAlignmentY(0.0F);
                        accEmailLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 255), 2, true));
                        accEmailLabel.setOpaque(true);
                        accEmailLabel.setPreferredSize(new java.awt.Dimension(250, 30));
                        if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                        {
                            accEmailLabel.setText("Account Email: " + SignupFrame.userAccount.getPaybuddy().emailGetter());
                        }
                        else
                        {
                            accEmailLabel.setText("Guest");
                        }
                        accEmailPanel.add(accEmailLabel);

                        accountMainPanel.add(accEmailPanel);

                        accNumPanel.setBackground(new java.awt.Color(255, 255, 255));

                        Account_Label_Number.setBackground(new java.awt.Color(255, 255, 255));
                        Account_Label_Number.setFont(accNameLabel.getFont());
                        Account_Label_Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Account_Label_Number.setText("Account Number");
                        Account_Label_Number.setToolTipText("");
                        Account_Label_Number.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        Account_Label_Number.setDoubleBuffered(true);
                        Account_Label_Number.setOpaque(true);
                        Account_Label_Number.setPreferredSize(new java.awt.Dimension(250, 30));
                        if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                        {
                            Account_Label_Number.setText("Account Number: " + SignupFrame.userAccount.getPaybuddy().numberGetter());
                        }
                        else
                        {
                            Account_Label_Number.setText("Guest Number");
                        }
                        accNumPanel.add(Account_Label_Number);

                        accountMainPanel.add(accNumPanel);

                        accPwPanel.setBackground(new java.awt.Color(255, 255, 255));

                        Account_Label_Password.setBackground(new java.awt.Color(255, 255, 255));
                        Account_Label_Password.setFont(accNameLabel.getFont());
                        Account_Label_Password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        Account_Label_Password.setText("Password");
                        Account_Label_Password.setAlignmentY(0.0F);
                        Account_Label_Password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        Account_Label_Password.setOpaque(true);
                        Account_Label_Password.setPreferredSize(new java.awt.Dimension(250, 30));
                        if(SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
                        {
                            Account_Label_Password.setText("Account Email: " + SignupFrame.userAccount.getPaybuddy().pwGetter());
                        }
                        else
                        {
                            Account_Label_Password.setText("Guest Password");
                        }
                        accPwPanel.add(Account_Label_Password);

                        accountMainPanel.add(accPwPanel);

                        deletePanel.setBackground(new java.awt.Color(255, 255, 255));
                        deletePanel.setPreferredSize(new java.awt.Dimension(138, 50));
                        deletePanel.setLayout(new javax.swing.BoxLayout(deletePanel, javax.swing.BoxLayout.Y_AXIS));

                        deleteButton.setBackground(new java.awt.Color(153, 51, 255));
                        deleteButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-B", 0, 14)); // NOI18N
                        deleteButton.setText("Perish account");
                        deleteButton.setAlignmentX(0.5F);
                        deleteButton.addActionListener(f ->
                            {
                                dispose();
                                new SignupFrame().setVisible(true);
                            });
                            deletePanel.add(deleteButton);

                            accountMainPanel.add(deletePanel);

                            accountPanel.add(accountMainPanel, java.awt.BorderLayout.CENTER);

                            jPanel5.setBackground(new java.awt.Color(204, 204, 255));
                            jPanel5.setMinimumSize(new java.awt.Dimension(100, 10));
                            jPanel5.setPreferredSize(new java.awt.Dimension(100, 10));
                            accountPanel.add(jPanel5, java.awt.BorderLayout.LINE_END);

                            leftPurplePanel.setBackground(new java.awt.Color(204, 204, 255));
                            leftPurplePanel.setPreferredSize(new java.awt.Dimension(100, 10));
                            accountPanel.add(leftPurplePanel, java.awt.BorderLayout.LINE_START);

                            designPanel.add(accountPanel, "card7");

                            imageLabel.setBackground(new java.awt.Color(153, 0, 51));
                            imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                            imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
                            imageLabel.setPreferredSize(new java.awt.Dimension(500, 546));
                            designPanel.add(imageLabel, "card2");

                            menuPanel.add(designPanel, java.awt.BorderLayout.CENTER);

                            getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);

                            pack();
                            setLocationRelativeTo(null);
                        }// </editor-fold>//GEN-END:initComponents

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ewallet_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Account_Label_Number;
    private javax.swing.JLabel Account_Label_Password;
    private javax.swing.JTextField Deposit_Amount;
    private javax.swing.JPanel Deposit_Main_Panel;
    private javax.swing.JPanel Deposit_Top_Border;
    private javax.swing.JLabel Enter_Amounr_Label;
    private javax.swing.JLabel accDetailsPanel;
    private javax.swing.JLabel accEmailLabel;
    private javax.swing.JPanel accEmailPanel;
    private javax.swing.JLabel accNameLabel;
    private javax.swing.JPanel accNamePanel;
    private javax.swing.JPanel accNumPanel;
    private javax.swing.JPanel accPwPanel;
    private javax.swing.JButton accountButton;
    private javax.swing.JButton accountButton1;
    private javax.swing.JPanel accountMainPanel;
    private javax.swing.JLabel accountMoney;
    private javax.swing.JLabel accountName;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel accountTopBorder;
    private javax.swing.JPanel buttonUpTop;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cedLabel;
    private javax.swing.JLabel cliffLabel;
    private javax.swing.JPanel creatorsPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel deletePanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel designPanel;
    private javax.swing.JPanel despositPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel headerButtonsPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel leftPurplePanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel robiLabel;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JLabel wilLabel;
    // End of variables declaration//GEN-END:variables
    
    //my variable declarations
    private String currentCard = "card2";
    //end of my variable declarations
    
    //user methods
    private String getPreviousCard(String current) {
        return switch (current) 
        {
        case "card4" -> "card2";
        case "card2" -> "card4";
        default -> "card1";
        };
    }
    
    private Image setImageIcon()
    {
        java.net.URL url = getClass().getResource("/main/resources/logo100x67.png");
        if(url != null)
        {
            return new ImageIcon(url).getImage();
        }
        else
        {
            return null;
        }
    }
    //end of user methods
}

class paybuddyAccount
{
        private paybuddy userAccount;
        
        public paybuddyAccount(paybuddy userAccount) 
        {
            this.userAccount = userAccount;
        }
        
        public paybuddy getPaybuddy()
        {
            return this.userAccount;
        }
}