/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fab.ewallet_project;

import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author cedri
 */



public class Ewallet_frame extends javax.swing.JFrame {

    /**
     * Creates new form e-wallet_frame
     */
    public Ewallet_frame() {
        initComponents();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        buttonUpTop = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        headerButtonsPanel = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(60, 0), new java.awt.Dimension(32767, 0));
        accountName = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        accountMoney = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jButton7 = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(32767, 0));
        menuPanel = new javax.swing.JPanel();
        buttonsPanel = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 50));
        transferButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        depositButton = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10));
        accountButton = new javax.swing.JButton();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        accountButton1 = new javax.swing.JButton();
        designPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        creatorsPanel = new javax.swing.JPanel();
        wilLabel = new javax.swing.JLabel();
        robiLabel = new javax.swing.JLabel();
        cliffLabel = new javax.swing.JLabel();
        cedLabel = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        despositPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paybuddy");
        setIconImage(setImageIcon());

        buttonUpTop.setBackground(new java.awt.Color(204, 204, 204));
        buttonUpTop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        buttonUpTop.setMaximumSize(new java.awt.Dimension(32767, 100));
        buttonUpTop.setPreferredSize(new java.awt.Dimension(883, 100));
        buttonUpTop.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo100x67.png"))); // NOI18N
        logoLabel.setText("PayBuddy");
        logoLabel.setToolTipText("");
        logoLabel.setMaximumSize(new java.awt.Dimension(250, 63));
        logoLabel.setMinimumSize(new java.awt.Dimension(120, 63));
        logoLabel.setPreferredSize(new java.awt.Dimension(250, 63));
        logoLabel.setRequestFocusEnabled(false);
        buttonUpTop.add(logoLabel, java.awt.BorderLayout.LINE_START);

        headerButtonsPanel.setBackground(new java.awt.Color(204, 204, 204));
        headerButtonsPanel.setMinimumSize(new java.awt.Dimension(500, 100));
        headerButtonsPanel.setLayout(new javax.swing.BoxLayout(headerButtonsPanel, javax.swing.BoxLayout.X_AXIS));
        headerButtonsPanel.add(filler4);

        accountName.setBackground(new java.awt.Color(102, 0, 0));
        accountName.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        accountName.setText("accountName");
        accountName.setAlignmentX(0.5F);
        if(SignupFrame.userAccount !=null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountName.setText("Hello, " + SignupFrame.userAccount.getPaybuddy().nameGetter() + "!");
        }
        else 
        {
            accountName.setText("Hello, Guest!");
        }
        headerButtonsPanel.add(accountName);
        headerButtonsPanel.add(filler5);

        accountMoney.setBackground(new java.awt.Color(102, 0, 0));
        accountMoney.setFont(accountName.getFont());
        accountMoney.setText("accountMoney");
        accountMoney.setAlignmentX(0.5F);
        accountMoney.setMaximumSize(new java.awt.Dimension(125, 20));
        accountMoney.setMinimumSize(new java.awt.Dimension(125, 20));
        accountMoney.setPreferredSize(new java.awt.Dimension(125, 20));
        if (SignupFrame.userAccount != null && SignupFrame.userAccount.getPaybuddy() != null)
        {
            accountMoney.setText("- P" + SignupFrame.userAccount.getPaybuddy().moneyGetter());
        }
        else
        {
            accountMoney.setText("P 0.00");
        }
        headerButtonsPanel.add(accountMoney);
        headerButtonsPanel.add(filler6);

        jButton7.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 12)); // NOI18N
        jButton7.setText("Who made PayBuddy?");
        jButton7.setMaximumSize(new java.awt.Dimension(149, 40));
        jButton7.setPreferredSize(new java.awt.Dimension(180, 30));
        headerButtonsPanel.add(jButton7);
        jButton7.addActionListener(e -> {
            if(currentCard.equals("card2"))
            {
                jButton7.setText("Switch back?");
            }
            else if(currentCard.equals("card4"))
            {
                jButton7.setText("Who made PayBuddy?");
            }
            String targetCard = getPreviousCard(currentCard);
            ((CardLayout)designPanel.getLayout()).show(designPanel, targetCard);
            currentCard = targetCard;
        });
        headerButtonsPanel.add(filler7);

        buttonUpTop.add(headerButtonsPanel, java.awt.BorderLayout.LINE_END);

        getContentPane().add(buttonUpTop, java.awt.BorderLayout.PAGE_START);

        menuPanel.setLayout(new java.awt.BorderLayout());

        buttonsPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonsPanel.setPreferredSize(new java.awt.Dimension(300, 461));
        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.Y_AXIS));
        buttonsPanel.add(filler3);

        transferButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
        transferButton.setText("Transfer");
        transferButton.setAlignmentX(0.5F);
        transferButton.setMaximumSize(new java.awt.Dimension(120, 70));
        transferButton.setPreferredSize(new java.awt.Dimension(75, 100));
        buttonsPanel.add(transferButton);
        transferButton.addActionListener(e ->
            {
                ((CardLayout)designPanel.getLayout()).show(designPanel, "card5");
            });
            buttonsPanel.add(filler1);

            depositButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
            depositButton.setText("Deposit");
            depositButton.setAlignmentX(0.5F);
            depositButton.setMaximumSize(new java.awt.Dimension(120, 70));
            depositButton.setPreferredSize(new java.awt.Dimension(75, 100));
            buttonsPanel.add(depositButton);
            depositButton.addActionListener(e ->
                {
                    ((CardLayout)designPanel.getLayout()).show(designPanel, "card6");
                });
                buttonsPanel.add(filler2);

                accountButton.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                accountButton.setText("Account");
                accountButton.setAlignmentX(0.5F);
                accountButton.setMaximumSize(new java.awt.Dimension(120, 70));
                accountButton.setPreferredSize(new java.awt.Dimension(75, 100));
                buttonsPanel.add(accountButton);
                accountButton.addActionListener(e ->
                    {
                        ((CardLayout)designPanel.getLayout()).show(designPanel, "card7");
                    });
                    buttonsPanel.add(filler10);

                    accountButton1.setBackground(new java.awt.Color(255, 153, 153));
                    accountButton1.setFont(new java.awt.Font("UD Digi Kyokasho NK-R", 0, 18)); // NOI18N
                    accountButton1.setText("Exit");
                    accountButton1.setAlignmentX(0.5F);
                    accountButton1.setMaximumSize(new java.awt.Dimension(120, 70));
                    accountButton1.setPreferredSize(new java.awt.Dimension(75, 100));
                    buttonsPanel.add(accountButton1);
                    accountButton1.addActionListener(e ->
                        {
                            System.exit(0);
                        });

                        menuPanel.add(buttonsPanel, java.awt.BorderLayout.LINE_START);

                        designPanel.setBackground(new java.awt.Color(102, 102, 102));
                        designPanel.setLayout(new java.awt.CardLayout());

                        imageLabel.setBackground(new java.awt.Color(153, 0, 51));
                        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
                        imageLabel.setPreferredSize(new java.awt.Dimension(500, 546));
                        designPanel.add(imageLabel, "card2");

                        creatorsPanel.setBackground(new java.awt.Color(102, 102, 102));
                        creatorsPanel.setLayout(new java.awt.GridLayout(2, 2));

                        wilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        wilLabel.setText("wil");
                        creatorsPanel.add(wilLabel);

                        robiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        robiLabel.setText("robi");
                        creatorsPanel.add(robiLabel);

                        cliffLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cliffLabel.setText("cliff");
                        creatorsPanel.add(cliffLabel);

                        cedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                        cedLabel.setText("ced");
                        creatorsPanel.add(cedLabel);

                        designPanel.add(creatorsPanel, "card4");

                        transferPanel.setBackground(new java.awt.Color(255, 255, 255));

                        jLabel1.setText("transfer");
                        transferPanel.add(jLabel1);

                        designPanel.add(transferPanel, "card5");

                        despositPanel.setBackground(new java.awt.Color(255, 255, 255));

                        jLabel2.setText("deposit");
                        despositPanel.add(jLabel2);

                        designPanel.add(despositPanel, "card6");

                        jLabel3.setText("account");
                        accountPanel.add(jLabel3);

                        designPanel.add(accountPanel, "card7");

                        menuPanel.add(designPanel, java.awt.BorderLayout.CENTER);

                        getContentPane().add(menuPanel, java.awt.BorderLayout.CENTER);

                        pack();
                        setLocationRelativeTo(null);
                    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ewallet_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ewallet_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton accountButton1;
    private javax.swing.JLabel accountMoney;
    private javax.swing.JLabel accountName;
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel buttonUpTop;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel cedLabel;
    private javax.swing.JLabel cliffLabel;
    private javax.swing.JPanel creatorsPanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JPanel designPanel;
    private javax.swing.JPanel despositPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel headerButtonsPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel robiLabel;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JLabel wilLabel;
    // End of variables declaration//GEN-END:variables
    
    //my variable declarations
    private String currentCard = "card2";
    //end of my variable declarations
    
    //user methods
    private String getPreviousCard(String current) {
        return switch (current) 
        {
        case "card4" -> "card2";
        case "card2" -> "card4";
        default -> "card1";
        };
    }
    
    private Image setImageIcon()
    {
        java.net.URL url = getClass().getResource("/main/resources/logo100x67.png");
        if(url != null)
        {
            return new ImageIcon(url).getImage();
        }
        else
        {
            return null;
        }
    }
    //end of user methods
}

class paybuddyAccount
{
        private paybuddy userAccount;
        
        public paybuddyAccount(paybuddy userAccount) 
        {
            this.userAccount = userAccount;
        }
        
        public paybuddy getPaybuddy()
        {
            return this.userAccount;
        }
}