package com.fab.ewallet_project;

import com.fab.ewallet_project.paybuddyAccount.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dane Zee Clarizze G
 */
public class SignupFrame extends javax.swing.JFrame {

    /**
     * Creates new form Sign_UP
     */
    public SignupFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    static paybuddyAccount userAccount;
    private paybuddy paybud;
    private boolean pwVisibility = false;

    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signupPanel = new javax.swing.JPanel();
        signupLabel = new javax.swing.JLabel();
        signupPanel2 = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 15));
        usernameLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 50));
        emailLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 50));
        phonenumLabel = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 50));
        passwordLabel = new javax.swing.JLabel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 90));
        quitButton = new javax.swing.JButton();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 1), new java.awt.Dimension(0, 10));
        textPanel = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 20));
        usernameField = new javax.swing.JTextField();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        emailField = new javax.swing.JTextField();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        numberField = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20));
        passwordField = new javax.swing.JPasswordField();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 20));
        javax.swing.JButton showpassBut = new javax.swing.JButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 20));
        javax.swing.JButton signupButton = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 20));

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP ON PAYBUDDY");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(621, 400));
        setUndecorated(true);
        setResizable(false);

        logoPanel.setBackground(new java.awt.Color(153, 153, 255));
        logoPanel.setMinimumSize(new java.awt.Dimension(70, 67));
        logoPanel.setName(""); // NOI18N
        logoPanel.setPreferredSize(new java.awt.Dimension(150, 400));
        logoPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo100x67.png"))); // NOI18N
        logoPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(logoPanel, java.awt.BorderLayout.LINE_START);

        signupPanel.setLayout(new java.awt.BorderLayout());

        signupLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signupLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signupLabel.setText("PAYBUDDY SIGN UP");
        signupLabel.setPreferredSize(new java.awt.Dimension(143, 80));
        signupPanel.add(signupLabel, java.awt.BorderLayout.PAGE_START);

        signupPanel2.setLayout(new java.awt.GridLayout(1, 2));

        infoPanel.setLayout(new javax.swing.BoxLayout(infoPanel, javax.swing.BoxLayout.Y_AXIS));
        infoPanel.add(filler1);

        usernameLabel.setFont(new java.awt.Font("G112 Art light", 0, 18)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Username: ");
        usernameLabel.setAlignmentX(0.5F);
        infoPanel.add(usernameLabel);
        infoPanel.add(filler2);

        emailLabel.setFont(usernameLabel.getFont());
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email: ");
        emailLabel.setAlignmentX(0.5F);
        infoPanel.add(emailLabel);
        infoPanel.add(filler3);

        phonenumLabel.setFont(usernameLabel.getFont());
        phonenumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phonenumLabel.setText("Phone number: ");
        phonenumLabel.setAlignmentX(0.5F);
        infoPanel.add(phonenumLabel);
        infoPanel.add(filler4);

        passwordLabel.setFont(usernameLabel.getFont());
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password: ");
        passwordLabel.setAlignmentX(0.5F);
        infoPanel.add(passwordLabel);
        infoPanel.add(filler11);

        quitButton.setBackground(new java.awt.Color(255, 153, 153));
        quitButton.setFont(signupButton.getFont());
        quitButton.setText("CANCEL");
        quitButton.setToolTipText("");
        quitButton.setAlignmentX(0.5F);
        infoPanel.add(quitButton);
        quitButton.addActionListener(e ->
            {
                System.exit(0);
            });
            infoPanel.add(filler12);

            signupPanel2.add(infoPanel);

            textPanel.setLayout(new javax.swing.BoxLayout(textPanel, javax.swing.BoxLayout.Y_AXIS));
            textPanel.add(filler10);

            usernameField.setMinimumSize(new java.awt.Dimension(64, 20));
            usernameField.setPreferredSize(new java.awt.Dimension(64, 20));
            textPanel.add(usernameField);
            textPanel.add(filler5);

            emailField.setMinimumSize(new java.awt.Dimension(64, 20));
            emailField.setPreferredSize(new java.awt.Dimension(64, 20));
            textPanel.add(emailField);
            textPanel.add(filler6);

            numberField.setMinimumSize(new java.awt.Dimension(64, 20));
            numberField.setPreferredSize(new java.awt.Dimension(64, 20));
            textPanel.add(numberField);
            textPanel.add(filler7);

            passwordField.setEchoChar('•');
            passwordField.setMinimumSize(new java.awt.Dimension(64, 20));
            passwordField.setPreferredSize(new java.awt.Dimension(64, 20));
            textPanel.add(passwordField);
            textPanel.add(filler8);

            showpassBut.addActionListener(f ->
                {
                    if(showpassBut.getText().equals("Show password?"))
                    {
                        passwordField.setEchoChar((char)0);
                        showpassBut.setText("Hide password?");
                    }
                    else
                    {
                        passwordField.setEchoChar('•');
                        showpassBut.setText("Show password?");
                    }
                });
                showpassBut.setBackground(new java.awt.Color(204, 204, 204));
                showpassBut.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
                showpassBut.setText("Show password?");
                showpassBut.setAlignmentX(0.5F);
                showpassBut.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        showpassButActionPerformed(evt);
                    }
                });
                textPanel.add(showpassBut);
                textPanel.add(filler13);

                signupButton.addActionListener(f ->
                    {
                        if(usernameField.getText().equals("") && emailField.getText().equals("") && numberField.getText().equals("") && passwordField.getText().equals(""))
                        {
                            javax.swing.JOptionPane.showMessageDialog(null,"Please fill out all fields!","",javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            paybud = new paybuddy(usernameField.getText(),emailField.getText(),numberField.getText(),passwordField.getText());
                            userAccount = new paybuddyAccount(paybud);
                            javax.swing.JOptionPane.showMessageDialog(null, "Signed up! Opening menu", "", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                            dispose();

                            new Ewallet_frame().setVisible(true);
                        }
                    });
                    signupButton.setBackground(new java.awt.Color(153, 153, 255));
                    signupButton.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
                    signupButton.setText("SIGN UP");
                    signupButton.setAlignmentX(0.5F);
                    signupButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            signupButtonActionPerformed(evt);
                        }
                    });
                    textPanel.add(signupButton);
                    textPanel.add(filler9);

                    signupPanel2.add(textPanel);

                    signupPanel.add(signupPanel2, java.awt.BorderLayout.CENTER);

                    getContentPane().add(signupPanel, java.awt.BorderLayout.CENTER);

                    setSize(new java.awt.Dimension(621, 400));
                    setLocationRelativeTo(null);
                }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupButtonActionPerformed

    private void showpassButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showpassButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JTextField numberField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phonenumLabel;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel signupLabel;
    private javax.swing.JPanel signupPanel;
    private javax.swing.JPanel signupPanel2;
    private javax.swing.JPanel textPanel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

    //user defined variables
    //end of user defined variables
    
    //user defined methods
    void showPassword()
    {
        if(!pwVisibility)
        {
            pwVisibility = true;
            passwordField.setEchoChar((char)0);
        }
        else
        {
            pwVisibility = false;
            passwordField.setEchoChar('•');
        }
    };
    //end of user defined methods
}

//ROBI AND WIL DIS IS FOR U
class paybuddy implements E_walletFunctions
{
    private String accountName;
    private int accountMoney;
    
    private String email;
    private String number;
    private String password;
            
    paybuddy(String accountName, String email, String number, String password)
    {
        this.accountName = accountName;
        this.email = email;
        this.number = number;
        this.password  = password;
    }
    
    //getter methods
    public String nameGetter()
    {
        return this.accountName;
    }
    
    public String emailGetter()
    {
        return this.email;
    }
    
    public String numberGetter()
    {
        return this.number;
    }
    
    public String pwGetter()
    {
        return this.password;
    }
    
    public int moneyGetter()
    {
        return this.accountMoney;
    }
    //end of getter methods
    
    //setter methods
    public void nameSetter(String name)
    {
        this.accountName = name;
    }
    
    public void emailSetter(String email)
    {
        this.email = email;
    }
    
    public void numberSetter(String number)
    {
        this.number = number;
    }
    
    public void pwSetter(String pw)
    {
        this.password = pw;
    }
    
    public void moneySetter(int money)
    {
        this.accountMoney = money;
    }
            
    //end of setter methods
    
    @Override
    public void transfer()
    {
        
    }
    
    @Override
    public void deposit(Ewallet_frame f)
    {
        moneySetter(Integer.parseInt(f.getAmountField().getText()));
        f.getMoneyLabel().setText(Integer.toString(moneyGetter()));
    }
    
    @Override
    public void account()
    {
        
    }
}